ProyectoT3/Models/Ejercicio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoT3.Models
{
    public class Ejercicio
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string LinkVideo { get; set; }
    }
}

ProyectoT3/Controllers/EjerciciosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ProyectoT3.Models;
using ProyectoT3.DB;
using ProyectoT3.Controllers.Strategy;
using Microsoft.AspNetCore.Authorization;

namespace ProyectoT3.Controllers
{
    [Authorize]
    public class infEjercicio//para mostrar los ejercicios de la rutina con sus tiempos en la vista
    {
        public string NombreEjercicio { get; set; }
        public int TiempoEjercicio { get; set; }
        public string LinkVideo { get; set; }
    }
    public class InfoRutina{
        public List<ListaEjercicios> listaDeEjercicios { get; set; }
        public List<Ejercicio> losEjercicios { get; set; }
    }
    public class InfRutinaTotal
    {
        public List<ListaEjercicios> ejerciciosRutina { get; set; }
        public List<Ejercicio> ejercicios { get; set; }
        public int duracionRutina { get; set; }
        public string Nive { get; set; }
    }
    public class informacionRutina//<<<<<<<<<<<<<<<<<<<<<<<<<
    {
        public List<Rutina> listaRutinas { get; set; }
        public List<ListaEjercicios> ListaEjercicios { get; set; }
        public string Nombre { get; set; }
    }
    [Authorize]
    public class EjerciciosController : Controller
    {
        public static InfRutinaTotal laRutina = new InfRutinaTotal();
        private Context _contexto;
        public EjerciciosController(Context _context)
        {
            this._contexto = _context;
        }

        public List<infEjercicio> ElegirRutina( IEstrategia estrategia)
        {
            ContextoS _context = new ContextoS(this._contexto);
            _context.setEstrategia(estrategia);
            

            List<ListaEjercicios> ejercicios = _context.creaRutina();
            List<Ejercicio> listEjerccios = new List<Ejercicio>();
            List<infEjercicio> listInfEjercicio = new List<infEjercicio>();
            Ejercicio ejercicio;
            infEjercicio infoEjercicio;
            foreach (ListaEjercicios lEjer in ejercicios)
            {
                ejercicio = _contexto.ejercicios.First(e => e.Id == lEjer.IdEjercicio);
                infoEjercicio = new infEjercicio()
                {
                    NombreEjercicio = ejercicio.Nombre,
                    TiempoEjercicio = lEjer.Tiempo,
                    LinkVideo = ejercicio.LinkVideo
                };
                //listEjerccios.Add(_contexto.ejercicios.First(e=>e.Id == lEjer.IdEjercicio));
                listEjerccios.Add(ejercicio);
                listInfEjercicio.Add(infoEjercicio);

            }
            //Tiempo total de la lista
            int tiempoTotal = 0;
            foreach(ListaEjercicios e in ejercicios)
            {
                tiempoTotal += e.Tiempo;
            }

            InfoRutina ejerciciosRutina = new InfoRutina()
            {
                listaDeEjercicios = ejercicios,
                losEjercicios = listEjerccios
            };

            setRutina(tiempoTotal, listEjerccios, ejercicios);

            return listInfEjercicio;
        }
        [HttpGet]
        public IActionResult nuevaRutina()
        {
            return View("ElegirRutina");
        }
        //Rutina páginas después de login
        public IActionResult muestraRutinas()
        {



            var user = GetLoggedUser();
            var Rutinas = _contexto.rutina.Where(r => r.IdUser == GetLoggedUser().Id);
            var Ejercicios = _contexto.ejercicios;
            var ListEjercicios = _contexto.listaEjerciciosCtxt;
            List<Rutina> listaRutinas = new List<Rutina>();
            List<ListaEjercicios> listaEjercicios = new List<ListaEjercicios>();
            //Rutinas del usaurio
            foreach (Rutina rutina in Rutinas)
            {
                Rutina newRutina = Rutinas.First(r=>r.Id == rutina.Id);
                listaRutinas.Add(newRutina);
            }

            List<Ejercicio> listEjerciciosRutina = new List<Ejercicio>();
            //ejercicios de la rutina
            foreach (Rutina rutina in listaRutinas)
            {
                listaEjercicios = ListEjercicios.Where(e => e.IdRutina == rutina.Id).ToList();
            }
            informacionRutina rutinas = new informacionRutina()
            {
                listaRutinas = listaRutinas,
                ListaEjercicios = listaEjercicios
            };

            return View("muestraRutinas", rutinas);
        }
        [HttpGet]
        public IActionResult registraRutinaForm()
        {
            return View();
        }
        //
        [HttpPost]
        public IActionResult registrarRutina(string nombre, string Nivel)
        {
            ContextoS _context = new ContextoS(this._contexto);
            
            //guardamos la rutina para luego obtener su Id
            Rutina rut = new Rutina()
            {
                Nombre = nombre,
                IdUser = GetLoggedUser().Id
            };
            _contexto.rutina.Add(rut);
            _contexto.SaveChanges();

            //escogemos la estrategia para los ejercicios
            switch (Nivel)
            {
                case "Principiante": _context.setEstrategia(new Principiante(this._contexto)); break;
                case "Intermedio": _context.setEstrategia(new Intermedio(this._contexto)); break;
                case "Avanzado": _context.setEstrategia(new Avanzado(this._contexto)); break;
            }
            //Obtenemos los ejercicios
            List<infEjercicio> listInfEjercicio = ElegirRutina(_context.getEstrategia());
            registraRutina();
            return View("ElegirRutina", listInfEjercicio);
        }
        //registra la rutina
        [HttpPost]
        public void registraRutina()
        {
            
            var rutinaTemp = _contexto.rutina;
            List<Rutina> lTemRutina = rutinaTemp.ToList();
            Rutina ruti = lTemRutina.LastOrDefault();

            foreach(ListaEjercicios ejercicio in laRutina.ejerciciosRutina)
            {
                ejercicio.IdRutina = ruti.Id;
                _contexto.listaEjerciciosCtxt.Add(ejercicio);
            }
            _contexto.SaveChanges();

            //return RedirectToAction("ElegirRutina",_contexto);
        }
        public IActionResult ListaEjerciciosRutina(int id)
        {
            var user = GetLoggedUser();
            //var Rutinas = _contexto.rutina.FirstOrDefault(r => r.IdUser == GetLoggedUser().Id);
            var ListEjercicios = _contexto.listaEjerciciosCtxt;

            List<ListaEjercicios> lista = ListEjercicios.ToList();
            List<Rutina> listaRutinas = new List<Rutina>();
            List<ListaEjercicios> listaEjercicios = new List<ListaEjercicios>();
            
            //Rutinas del usaurio
            List<Ejercicio> listEjerciciosRutina = new List<Ejercicio>();
            listaEjercicios = ListEjercicios.Where(l=>l.IdRutina == id).ToList();
            return View("ListaEjerciciosRutina", listaEjercicios);
        }

        //Otras funciones
        public void setRutina(int duracion, List<Ejercicio> ejercicios, List<ListaEjercicios> listaEjercicios)
        {
            laRutina.ejercicios = ejercicios;
            laRutina.ejerciciosRutina = listaEjercicios;
        }
        private Usuario GetLoggedUser()
        {
            var claim = HttpContext.User.Claims.First();
            string username = claim.Value;
            var user = _contexto.usuarios.First(o => o.UsuarioU == username);
            return user;
        }
    }
}

ProyectoT3/Views/Ejercicios/ElegirRutina.cshtml
<html>
<head>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>

    <div>
        <p>Ejercicios del la rutina</p>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Duración</th>
                    <th scope="col">Link del Video</th>
                </tr>
            </thead>
            <tbody>
                @{ int contador = 0;}
                @foreach (var ej in Model)
                {
                    contador++;
                    <tr>
                        <th scope="row">@contador</th>
                        <td>@ej.NombreEjercicio</td>
                        <td> @ej.TiempoEjercicio</td>
                        <td><a href="@ej.LinkVideo">@ej.LinkVideo</a></td>
                    </tr>
                }
            </tbody>
        </table>

</div>
    <br />
    <hr />
    <div>
        <a href="https://localhost:44396/Ejercicios/muestraRutinas" class="btn btn-warning">Ver Rutinas</a>
    </div>
    <br />
    <br />
    <hr />


</body>
</html>
<script type="text/javascript">
    //$('.Nivel').val('Principiante');
    $(document).ready(function () {

        var tp
        $('#OpcionesRutinas').on('change', function () {
            tp = $(this).val();
            //alert(tp);
            $('.Nivel').val(tp)
        })
    })
</script>

ProyectoT3/Views/Ejercicios/ListaEjerciciosRutina.cshtml
<html>
<head>

</head>
<body>
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Duración</th>
                    <th scope="col">Link del Video</th>
                </tr>
            </thead>
            <tbody>
                @{int contador = 0;}
                @foreach (ListaEjercicios ejercicio in Model)
                {
                    contador++;
                    <tr>
                        <th scope="row">@contador</th>
                        <td>@ejercicio.NombreEjercicio</td>
                        <td> @ejercicio.Tiempo</td>
                        <td><a href="@ejercicio.LinkVideo">@ejercicio.LinkVideo</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <br />
    <br />
    <hr />
    <div>
        <a href="https://localhost:44396/Ejercicios/muestraRutinas" class="btn btn-dark">Volver</a>
    </div>
</body>
</html>

ProyectoT3/Views/Ejercicios/muestraRutinas.cshtml
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
    <div>
        <a class="btn btn-dark" href="/Ejercicios/registraRutinaForm">Crear Rutinas</a>
    </div>
    <br />

    <div id="ListaRutinas">
        @foreach (var rutinas in Model.listaRutinas)
        {
            <div class="list-group">
                <a class="list-group-item" href="/Ejercicios/ListaEjerciciosRutina?id=@rutinas.Id">@rutinas.Nombre</a><br />
            </div>
        }
        </div>
</body>
</html>
<script>
    var rutin;
    var listaE;
    $(document).ready(function () {

        $("#rutina").on('click', function () {
            rutin = $(this).val();
        })
        listaE = @Model.ListaEjercicios

    })
    $('#listaE #ejercicio').each(function (indice, elemento) {

        console.log('El elemento con el índice ' + indice + ' contiene ' + $(elemento).text());
    });
</script>

    
   

ProyectoT3/Views/Ejercicios/registraRutinaForm.cshtml
<html>
<head>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
    <div>
        <form asp-controller="Ejercicios" asp-action="registrarRutina" method="post">
            <label class="form-label"><b>Nombre de la rutina</b> </label>
            <input type="text" class="form-control" name="nombre" placeholder="Nombre de la Rutina" value="Nueva Rutina" />
            <label class="form-label"><b>Nivel</b> </label>
            <input type="hidden" class="Nivel" name="Nivel" />
            <select class="form-select" id="OpcionesRutinas" >
                <option value="Principiante">Principiante</option>
                <option value="Intermedio">Intermedio</option>
                <option value="Avanzado">Avanzado</option>
            </select>
            <br />
            <input type="submit" class="btn btn-dark" value="Guardar" />
        </form>
        </div>
</body>
</html>
<script type="text/javascript">
    $('.Nivel').val('Principiante');

    $(document).ready(function () {

        var tp
        $('#OpcionesRutinas').on('change', function () {
            tp = $(this).val();
            $('.Nivel').val(tp)
        })
    })
</script>